In [68]:
import pandas as pd

In [69]:
df = pd.read_csv('data.csv')

In [70]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [71]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.4 KB

In [73]:
df.describe().round(2)

       Duration   Pulse  Maxpulse  Calories
count     32.00   32.00     32.00     30.00
mean      68.44  103.50    128.50    304.68
std       70.04    7.83     13.00     66.00
min       30.00   90.00    101.00    195.10
25%       60.00  100.00    120.00    250.70
50%       60.00  102.50    127.50    291.20
75%       60.00  106.50    132.25    343.98
max      450.00  130.00    175.00    479.00

In [74]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [75]:
df[df['Date'].isnull()] # Count missing values

    Duration Date  Pulse  Maxpulse  Calories
22        45  NaN    100       119     282.0

In [76]:

# Replace missing date at index row 2 with a specific date
df.loc[22, 'Date'] = '2020/12/22'

In [77]:
df['Date']

0     '2020/12/01'
1     '2020/12/02'
2     '2020/12/03'
3     '2020/12/04'
4     '2020/12/05'
5     '2020/12/06'
6     '2020/12/07'
7     '2020/12/08'
8     '2020/12/09'
9     '2020/12/10'
10    '2020/12/11'
11    '2020/12/12'
12    '2020/12/12'
13    '2020/12/13'
14    '2020/12/14'
15    '2020/12/15'
16    '2020/12/16'
17    '2020/12/17'
18    '2020/12/18'
19    '2020/12/19'
20    '2020/12/20'
21    '2020/12/21'
22      2020/12/22
23    '2020/12/23'
24    '2020/12/24'
25    '2020/12/25'
26        20201226
27    '2020/12/27'
28    '2020/12/28'
29    '2020/12/29'
30    '2020/12/30'
31    '2020/12/31'
Name: Date, dtype: str

In [78]:
df[df['Calories'].isnull()] # Count missing values

    Duration          Date  Pulse  Maxpulse  Calories
18        45  '2020/12/18'     90       112       NaN
28        60  '2020/12/28'    103       132       NaN

In [79]:
df['Calories'].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
Name: Calories, dtype: bool

In [80]:
df['Calories'].mean()

np.float64(304.68)

In [81]:
#Replacing missing values in column Calories with mean value
df['Calories'] = df['Calories'].fillna(df['Calories'].mean(), inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_8076\1704219699.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Calories'] = df['Calories'].fillna(df['Calories'].mean(), inplace=True)

In [82]:
df['Calories'].isnull().sum() # Count missing values

np.int64(0)

In [83]:
#changing the data type of the column Date to datetime format
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

In [84]:
df['Date'] = pd.to_datetime(df['Date'].astype(str).str.strip('\'"'))

Inserting two New Columns - 'Calories_per_min' and 'pulse_range'

In [92]:
df['Calories_per_min'] = df['Calories'] / df['Duration']

In [93]:
df['Pulse_Range'] = df['Maxpulse'] - df['Pulse']

In [94]:
df.head()

,Duration,Date,Pulse,Maxpulse,Calories,Calories_per_min,Pulse_Range
0,60,2020-12-01,110,130,409.1,6.818333,20
1,60,2020-12-02,117,145,479.0,7.983333,28
2,60,2020-12-03,103,135,340.0,5.666667,32
3,45,2020-12-04,109,175,282.4,6.275556,66
4,45,2020-12-05,117,148,406.0,9.022222,31

In [88]:

# df = df.iloc[:, :5]